const OPENAI_ENDPOINT = process.env.NEXT_PUBLIC_OPENAI_ENDPOINT ?? '';
const OPENAI_ENDPOINT_UPLOAD = OPENAI_ENDPOINT + 'upload/'
const OPENAI_ENDPOINT_CALL_GPT3 = OPENAI_ENDPOINT + 'generateRequireTesting/'
const OPENAI_ENDPOINT_CALL_GPT3_2 = OPENAI_ENDPOINT + 'generateOwnershipTesting/'
const OPENAI_ENDPOINT_CALL_GPT3_3 = OPENAI_ENDPOINT + 'generateExplanation/'
const OPENAI_ENDPOINT_CALL_SLEITHER = OPENAI_ENDPOINT + 'audit/'

export {
  OPENAI_ENDPOINT_UPLOAD,
  OPENAI_ENDPOINT_CALL_GPT3,
  OPENAI_ENDPOINT_CALL_GPT3_2,
  OPENAI_ENDPOINT_CALL_GPT3_3,
  OPENAI_ENDPOINT_CALL_SLEITHER,
};